const body=document.body,theme=document.getElementById('theme'),bg=document.getElementById('background'),cursorSel=document.getElementById('cursor'),effects=document.getElementById('effects'),range=document.getElementById('intensity'),intensityOut=document.getElementById('intensityOut'),blur=document.getElementById('blur'),radius=document.getElementById('radius'),speed=document.getElementById('speed'),textStyle=document.getElementById('textStyle'),blurOut=document.getElementById('blurOut'),radiusOut=document.getElementById('radiusOut'),speedOut=document.getElementById('speedOut'),preview=document.getElementById('preview'),spot=document.getElementById('spotlight'),stars=document.getElementById('stars'),customCursor=document.getElementById('customCursor'),cursorLabel=document.getElementById('cursorLabel'),trailLayer=document.getElementById('cursorTrailLayer'),card=document.getElementById('demoCard'),log=document.getElementById('log');
const toggles={hover:true,click:true,magnet:true,label:true,glass:true,pulse:true};let mx=innerWidth/2,my=innerHeight/2,px=mx,py=my,lastTrail=0;
function makeStars(){stars.innerHTML='';if(bg.value!=='stars')return;for(let i=0;i<150;i++){const s=document.createElement('i');s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.opacity=.15+Math.random()*.85;s.style.transform=`scale(${.5+Math.random()*2})`;stars.appendChild(s)}}
function apply(){body.className=theme.value;body.dataset.bg=bg.value;body.dataset.effects=effects.value;body.dataset.text=textStyle.value;body.style.setProperty('--intensity',(range.value/100).toFixed(2));body.style.setProperty('--blur',blur.value+'px');body.style.setProperty('--radius',radius.value+'px');body.style.setProperty('--speed',(100/Number(speed.value)).toFixed(2)+'s');intensityOut.textContent=range.value+'%';blurOut.textContent=blur.value+'px';radiusOut.textContent=radius.value+'px';speedOut.textContent=(Number(speed.value)/100).toFixed(2)+'x';makeStars();const c=cursorSel.value;customCursor.className='custom-cursor '+(c==='ring'?'cursor-ring':c==='dot'?'cursor-dot':c==='trail'?'cursor-trail':c==='cross'?'cursor-cross':c==='comet'?'cursor-comet':c==='heart'?'cursor-heart':'');body.style.cursor=c==='none'?'auto':'none';if(c==='none')customCursor.style.display='none';else customCursor.style.display='block';document.querySelector('.scanline').style.opacity=(effects.value==='glitch'||effects.value==='all')?.3:0;log.textContent=`${theme.options[theme.selectedIndex].text} / ${bg.options[bg.selectedIndex].text} / ${cursorSel.options[cursorSel.selectedIndex].text}`}
[theme,bg,cursorSel,effects,range,blur,radius,speed,textStyle].forEach(x=>x.addEventListener('input',apply));
document.querySelectorAll('.swatches button').forEach(b=>b.onclick=()=>{document.body.style.setProperty('--accent',b.dataset.c);log.textContent='Custom accent selected — '+b.dataset.c});
document.querySelectorAll('.toggle').forEach(b=>b.onclick=()=>{const k=b.dataset.toggle;toggles[k]=!toggles[k];b.classList.toggle('active',toggles[k]);log.textContent=`${k} ${toggles[k]?'enabled':'disabled'}`});
addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;spot.style.left=mx-preview.getBoundingClientRect().left+'px';spot.style.top=my-preview.getBoundingClientRect().top+'px';if(toggles.label&&cursorSel.value!=='none'){cursorLabel.classList.add('show');cursorLabel.style.left=mx+'px';cursorLabel.style.top=my+'px';cursorLabel.textContent=cursorSel.value==='comet'?'COMET':cursorSel.value==='heart'?'SPARK':'MOVE'}else cursorLabel.classList.remove('show');if(cursorSel.value!=='none'){customCursor.style.left=mx+'px';customCursor.style.top=my+'px'}if(toggles.hover&&effects.value!=='none'&&e.target.closest('.preview')){const r=preview.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;card.style.transform=`perspective(1000px) rotateX(${y/-45}deg) rotateY(${x/45}deg) translateZ(8px)`}else if(!e.target.closest('.preview'))card.style.transform='';if(cursorSel.value==='trail'&&performance.now()-lastTrail>28){lastTrail=performance.now();const t=document.createElement('i');t.style.left=mx+'px';t.style.top=my+'px';trailLayer.appendChild(t);t.animate([{opacity:.9,transform:'translate(-50%,-50%) scale(1)'},{opacity:0,transform:'translate(-50%,-50%) scale(.1)'}],{duration:500}).onfinish=()=>t.remove()}});
addEventListener('mouseleave',()=>cursorLabel.classList.remove('show'));
preview.addEventListener('mousemove',e=>{if(effects.value==='glitch'||effects.value==='all'){preview.style.setProperty('--gx',(e.offsetX/preview.clientWidth*100)+'%')}});
preview.addEventListener('mouseleave',()=>card.style.transform='');
function burst(x=mx,y=my,count=30){if(!toggles.click)return;for(let i=0;i<count;i++){const p=document.createElement('i');p.style.cssText=`position:fixed;left:${x}px;top:${y}px;width:${3+Math.random()*7}px;height:${3+Math.random()*7}px;border-radius:50%;background:var(--accent);z-index:999;pointer-events:none;box-shadow:0 0 14px var(--accent)`;document.body.appendChild(p);const a=Math.random()*6.28,d=40+Math.random()*240*(range.value/100);p.animate([{transform:'translate(-50%,-50%) scale(1)',opacity:1},{transform:`translate(calc(-50% + ${Math.cos(a)*d}px),calc(-50% + ${Math.sin(a)*d}px)) scale(.1)`,opacity:0}],{duration:450+Math.random()*450,easing:'cubic-bezier(.2,.7,.2,1)'}).onfinish=()=>p.remove()}}
document.addEventListener('click',e=>{if(e.target.closest('select,input,aside'))return;if(toggles.click)burst(e.clientX,e.clientY,18);if(e.target.closest('.magnetic-target')&&toggles.magnet)log.textContent='Magnetic interaction triggered ✦'});
document.querySelectorAll('.magnetic-target').forEach(el=>{el.addEventListener('mousemove',e=>{if(!toggles.magnet)return;const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)*.18,y=(e.clientY-r.top-r.height/2)*.18;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')});
document.getElementById('burst').onclick=()=>{burst(innerWidth/2,innerHeight/2,45);log.textContent='Effect burst created — real particles fired.'};
document.getElementById('randomize').onclick=()=>{const vals=['aurora','mesh','stars','grid','waves'];bg.value=vals[Math.floor(Math.random()*vals.length)];cursorSel.value=['ring','dot','trail','cross','comet','heart'][Math.floor(Math.random()*6)];effects.value=['all','glow','motion','glitch','particles'][Math.floor(Math.random()*5)];range.value=35+Math.floor(Math.random()*66);apply();burst(innerWidth/2,innerHeight/2,35);log.textContent='Surprise mode activated.'};
document.getElementById('reset').onclick=()=>{theme.value='pink';bg.value='aurora';cursorSel.value='ring';effects.value='all';range.value=70;blur.value=12;radius.value=28;speed.value=100;textStyle.value='normal';Object.keys(toggles).forEach(k=>toggles[k]=true);document.querySelectorAll('.toggle').forEach(b=>b.classList.add('active'));document.body.style.removeProperty('--accent');apply();log.textContent='Reset complete — ready to play.'};
apply();
// Extra Labs experiments
(()=>{
 const q=id=>document.getElementById(id), comp=q('demoComponent'), stage=q('componentStage');
 function compApply(){if(!comp)return;const r=q('xRadius').value,g=q('xGlow').value,sc=q('xScale').value,b=q('xBorder').value;comp.style.borderRadius=r+'px';comp.style.boxShadow=`0 0 ${g}px var(--accent)`;comp.style.transform=`scale(${sc/100})`;comp.style.borderWidth=b+'px'}
 ['xRadius','xGlow','xScale','xBorder'].forEach(id=>q(id)?.addEventListener('input',compApply));compApply();
 const type=q('typeStage');function typeApply(){if(!type)return;type.style.fontSize=q('tSize').value+'px';type.style.letterSpacing=q('tSpacing').value+'px';type.style.fontWeight=q('tWeight').value;type.style.textTransform=q('tTransform').value}['tSize','tSpacing','tWeight','tTransform'].forEach(id=>q(id)?.addEventListener('input',typeApply));typeApply();
 q('layoutSwap')?.addEventListener('click',()=>{q('miniLayout').style.gridTemplateColumns='2fr 1fr 1fr'});q('layoutStack')?.addEventListener('click',()=>{q('miniLayout').style.gridTemplateColumns='1fr';q('miniLayout').querySelectorAll('span').forEach(x=>x.style.height='70px')});
 const at=q('atmosphereStage');function atm(){if(!at)return;at.style.filter=`blur(${q('aBlur').value/10}px)`;at.style.opacity=q('aOpacity').value/100;at.style.background=`linear-gradient(${q('aAngle').value}deg,#ff5ca855,#8f5cff55,#49e4ff33)`;at.style.setProperty('--grain',q('aGrain').value)}['aBlur','aOpacity','aAngle','aGrain'].forEach(id=>q(id)?.addEventListener('input',atm));atm();
})();
