const matrix=document.getElementById('matrix');for(let i=0;i<98;i++){const x=document.createElement('i');if(Math.random()>.55)x.className='active';matrix.appendChild(x)}
const nodes=document.getElementById('nodes'),latency=document.getElementById('latency'),threat=document.getElementById('threat'),clock=document.getElementById('clock');let nodeValue=4821;setInterval(()=>{nodeValue+=Math.floor(Math.random()*15)-6;nodes.textContent=nodeValue.toLocaleString();latency.textContent=(9+Math.floor(Math.random()*8))+' ms';threat.textContent=(Math.random()*.05).toFixed(2);clock.textContent=new Date().toLocaleTimeString('en-GB')},1000);
function log(text,cls=''){const box=document.getElementById('terminalLog');const p=document.createElement('p');p.textContent='> '+text;p.className=cls;box.appendChild(p);box.scrollTop=box.scrollHeight}
document.getElementById('simulate').onclick=()=>{log('simulation.start()');let n=0;const t=setInterval(()=>{n+=20;document.getElementById('velocity').textContent='+'+(18.4+n/10).toFixed(1)+'%';if(n>=100){clearInterval(t);log('simulation.complete()','ok');document.getElementById('signalText').textContent='Simulation complete. All monitored paths remain inside optimal parameters.'}},120)};
document.getElementById('signal').onclick=()=>{const v=96+Math.floor(Math.random()*4);document.getElementById('signalValue').textContent=v+'%';document.getElementById('signalText').textContent='Signal amplified. Confidence recalculated across the active dataset.';log('ai.signal.amplify()','ok')};
document.getElementById('ping').onclick=()=>{document.querySelectorAll('#networkMap i').forEach((x,i)=>setTimeout(()=>x.animate([{transform:'scale(1)',boxShadow:'0 0 10px #48eaff'},{transform:'scale(2.2)',boxShadow:'0 0 30px #48eaff'},{transform:'scale(1)'}],{duration:500}),i*100));log('network.broadcastPing()','ok')};
document.getElementById('reroute').onclick=()=>{document.getElementById('velocity').textContent='+'+(20+Math.random()*10).toFixed(1)+'%';log('analytics.reroute(channel=07)','ok')};
document.getElementById('deployNow').onclick=()=>{const cells=[...document.querySelectorAll('.matrix i')];cells.forEach((c,i)=>setTimeout(()=>c.classList.add('active'),i*12));log('deploy.module(quantum-ui)','ok')};
document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');log('mode.set('+b.dataset.mode+')','ok')});
document.getElementById('terminalForm').onsubmit=e=>{e.preventDefault();const input=document.getElementById('terminalInput'),cmd=input.value.trim().toLowerCase();if(!cmd)return;log(cmd);const replies={scan:'network.scan() complete — 7 nodes healthy.',deploy:'deployment queue opened — 12 modules ready.',help:'commands: scan / deploy / simulate / status / clear',status:'all quantum systems nominal.',simulate:'simulation started — monitor the analytics panel.',clear:'terminal.clear()'};if(cmd==='clear'){document.getElementById('terminalLog').innerHTML='';}else log(replies[cmd]||'command not recognized. Try help.','ok');input.value=''};
document.getElementById('fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();document.getElementById('theme').onclick=()=>document.body.classList.toggle('alt');
